parameters:
    firecrawl.api_key: '%env(FIRECRAWL_API_KEY)%'
    openai.api_key: '%env(OPENAI_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Chose which scraper does its job here
    App\Service\ScraperInterface:
        alias: App\Service\SymfonyCrawlerScraper
        # Use Firecrawl :
        # alias: App\Service\Scraper\FirecrawlScraper

    App\Service\FirecrawlScraper:
        arguments:
            $apiKey: '%firecrawl.api_key%'

    App\Service\KeywordExtractorService:
        arguments:
            $openaiApiKey: '%openai.api_key%'
